
-- Nettoyer toutes les données existantes avant l'insertion
DELETE FROM order_items;
DELETE FROM orders;
DELETE FROM reviews;
DELETE FROM user_wishlist;
DELETE FROM game_tags;
DELETE FROM game_images;
DELETE FROM cart;
DELETE FROM addresses;
DELETE FROM games;
DELETE FROM users;
-- Insertion des 40 jeux complets
INSERT INTO games (id, title, platform, genre, price, rating, release_date, stock, description, cover_image, url_trailer, promo, popular) VALUES
('1', 'Cyberpunk 2077', 'PC', 'RPG', 59.99, 4.5, '2020-12-10', 12, 'Incarnez V, un mercenaire dans la mégalopole futuriste de Night City. Personnalisez votre cyberware, vos compétences et votre style de jeu pour survivre dans une ville obsédée par le pouvoir et la technologie. Avec Keanu Reeves dans le rôle de Johnny Silverhand.', '/assets/games/cover/cyberpunk.jpg', 'https://www.youtube.com/watch?v=8X2kIfS6fb8', true, false),
('2', 'Red Dead Redemption 2', 'PC', 'Aventure', 49.99, 4.7, '2018-10-26', 18, 'Vivez l''Amérique à la fin de l''ère du Far West. Incarnez Arthur Morgan, un hors-la-loi en fuite avec sa bande. Chassez, pêchez, braquez des banques et survivez dans un monde ouvert immense et réaliste. Une histoire épique sur la loyauté et la rédemption.', '/assets/games/cover/rdr2.jpg', 'https://www.youtube.com/watch?v=gmA6MrX81z4', false, false),
('3', 'The Witcher 3: Wild Hunt', 'PC', 'RPG', 39.99, 4.9, '2015-05-19', 20, 'Geralt de Rivia, chasseur de monstres légendaire, part à la recherche de Ciri, l''enfant de la prophétie. Explorez un continent déchiré par la guerre, combattez des créatures redoutables et prenez des décisions qui changeront le cours de l''histoire.', '/assets/games/cover/witcher3.jpg', 'https://www.youtube.com/watch?v=c0i88t0Kacs', false, true),
('4', 'Assassin''s Creed Valhalla', 'PC', 'Action', 54.99, 4.8, '2020-11-12', 10, 'Devenez Eivor, un fier guerrier viking élevé dans les légendes de bataille et de gloire. Explorez l''Angleterre médiévale, menez des raids, construisez votre colonie et gagnez votre place au Valhalla dans ce chapitre épique de la saga Assassin''s Creed.', '/assets/games/cover/valhalla.jpg', 'https://www.youtube.com/watch?v=ssrNcwxALS4', false, true),
('5', 'Grand Theft Auto V', 'PC', 'Action', 29.99, 4.8, '2013-09-17', 15, 'Explorez Los Santos, une métropole éclatante dans l''État de San Andreas. Incarnez trois criminels aux histoires entrelacées : Michael, Franklin et Trevor. Une satire mordante de la société américaine moderne avec un mode histoire captivant et GTA Online illimité.', '/assets/games/cover/gtav.jpg', 'https://www.youtube.com/watch?v=QkkoHAzjnUs', true, true),
('6', 'Call of Duty: Warzone', 'PC', 'FPS', 57.00, 4.8, '2020-12-22', 10, 'Battle royale intense dans l''univers de Call of Duty. Affrontez jusqu''à 150 joueurs dans la carte massive de Verdansk. Récupérez des contrats, personnalisez vos armes et soyez le dernier survivant dans cette expérience de combat tactique.', '/assets/games/cover/cod.jpg', 'https://www.youtube.com/watch?v=0E44DClsX5Q', false, true),
('7', 'Mortal Kombat 11', 'PC', 'Fighting', 44.99, 4.6, '2021-05-21', 15, 'Le combat ultime revient avec des graphismes époustouflants et une violence extrême. Personnalisez vos combattants préférés, découvrez une nouvelle histoire temporelle et maîtrisez des combos dévastateurs dans le jeu de combat le plus sanglant de la planète.', '/assets/games/cover/mk11.jpg', 'https://www.youtube.com/watch?v=UoTams2yc0s', false, false),
('8', 'Street Fighter 6', 'PC', 'Fighting', 59.99, 4.6, '2023-09-20', 15, 'La révolution du combat arrive ! Avec un nouveau système de combat innovant, un mode monde ouvert inédit et des graphismes next-gen. Rejoignez le Fighting Ground, le World Tour et le Battle Hub pour l''expérience Street Fighter ultime.', '/assets/games/cover/sf6.jpg', 'https://www.youtube.com/watch?v=1tBUsXIkG1A', false, false),
('9', 'EA Sports FC 24', 'PC', 'Sport', 69.99, 4.8, '2024-09-28', 10, 'L''ère nouvelle du football vidéo commence. Avec la technologie HyperMotionV, l''Opta optimisée et les styles de jeu PlayStyles, vivez le jeu le plus réaliste jamais créé. Plus de 19,000 joueurs, 700 équipes et 30 ligues.', '/assets/games/cover/fc24.jpg', 'https://www.youtube.com/watch?v=XhP3Xh4LMA8', false, true),
('10', 'Baldur''s Gate 3', 'PC', 'RPG', 59.99, 4.9, '2023-08-03', 8, 'Plongez dans un RPG épique où chaque choix compte. Créez votre personnage, formez votre groupe et explorez les Royaumes Oubliés dans cette aventure aux possibilités infinies. Basé sur les règles de D&D 5e, avec un système de combat tactique et des milliers de dialogues.', '/assets/games/cover/baldursgate3.jpg', 'https://www.youtube.com/watch?v=OcP0WdH7rTs', true, true),
('11', 'Valorant', 'PC', 'FPS', 39.00, 4.5, '2020-06-02', 75, 'FPS tactique 5v5 qui mélange précision au tir et compétences d''agents uniques. Chaque agent possède des capacités spéciales qui peuvent changer le cours d''une manche. Stratégie, teamwork et skill sont la clé pour dominer.', '/assets/games/cover/valorant.jpg', 'https://www.youtube.com/watch?v=lWr6dhTcu-E', false, false),
('12', 'Starfield', 'PC', 'RPG', 69.99, 4.3, '2023-09-06', 14, 'Le premier nouvel univers de Bethesda en 25 ans. Explorez plus de 1000 planètes, personnalisez votre vaisseau, recrutez un équipage et découvrez les secrets de la galaxie dans ce RPG spatial épique.', '/assets/games/cover/starfield.jpg', 'https://www.youtube.com/watch?v=kfYEiTdsyas', false, false),
('13', 'Diablo IV', 'PC', 'RPG', 69.99, 4.6, '2023-06-06', 11, 'Retournez dans le monde sombre de Sanctuary dans ce nouvel opus de Diablo. Affrontez les forces du mal, personnalisez votre héros avec des compétences et équipements légendaires, et explorez un monde ouvert persistant rempli de donjons et de secrets.', '/assets/games/cover/diablo4.jpg', 'https://www.youtube.com/watch?v=9bRWIdOMfro', false, false),
('14', 'Forza Horizon 5', 'PC', 'Racing', 59.99, 4.8, '2021-11-09', 9, 'Course en monde ouvert au Mexique avec des centaines de voiles. Explorez des paysages époustouflants, participez à des festivals de musique et devenez une star de la course dans le plus grand Horizon à ce jour.', '/assets/games/cover/forza5.jpg', 'https://www.youtube.com/watch?v=FYH9n37B7Yw', true, true),
('15', 'Dying Light 2: Stay Human', 'PC', 'RPG', 49.99, 4.8, '2023-09-28', 10, 'Survie dans un monde post-apocalyptique ravagé par des zombies. Utilisez le parkour pour explorer la ville, combattez des infectés et des factions hostiles, et prenez des décisions qui affectent le monde autour de vous.', '/assets/games/cover/dyinglight.jpg', 'https://www.youtube.com/watch?v=UwJAAy7tPhE', false, true),
('16', 'God of War Ragnarök', 'PlayStation 5', 'Action', 69.99, 4.8, '2022-11-09', 10, 'La suite épique de l''histoire de Kratos et Atreus dans la mythologie nordique. Affrontez des dieux et des créatures légendaires tout en explorant les Neuf Royaumes dans cette aventure émotionnelle intense.', '/assets/games/cover/gow.jpg', 'https://www.youtube.com/watch?v=EE-4GvjKcfs', false, true),
('17', 'The Last of Us Part II', 'PlayStation 5', 'Action', 59.99, 4.9, '2020-06-19', 8, 'Une aventure émotionnelle intense dans un monde post-apocalyptique. Suivez Ellie dans sa quête de vengeance à travers l''Amérique dévastée, où chaque décision a un prix et chaque combat est une lutte pour la survie.', '/assets/games/cover/lastofus2.jpg', 'https://www.youtube.com/watch?v=btmN-bWwv0A', false, true),
('18', 'EA Sports FC 25', 'PlayStation 5', 'Sport', 79.99, 4.3, '2024-09-27', 22, 'La nouvelle génération de football avec HyperMotionV et une IA améliorée. Profitez d''une expérience de jeu ultra-réaliste avec des animations fluides, une physique avancée et des modes de jeu innovants.', '/assets/games/cover/fifa25.jpg', 'https://www.youtube.com/watch?v=pBM2xyco_Kg', true, false),
('19', 'Spider-Man 2', 'PlayStation 5', 'Action', 69.99, 4.8, '2023-10-20', 12, 'Incarnez Peter Parker et Miles Morales dans cette aventure arachnéenne épique. Affrontez de nouveaux villains dangereux, explorez New York élargi et maîtrisez de nouvelles capacités dans le combat le plus dynamique de la série.', '/assets/games/cover/spiderman2.jpg', 'https://www.youtube.com/watch?v=qIQ3xNqkVC4', false, true),
('20', 'Horizon Forbidden West', 'PlayStation 5', 'Action', 69.99, 4.7, '2022-02-18', 14, 'Explorez l''Ouest interdit dans cette suite épique d''Horizon Zero Dawn. Aloy découvre de nouvelles terres, affronte des machines plus dangereuses et révèle des secrets qui pourraient changer le destin du monde.', '/assets/games/cover/horizon2.jpg', 'https://www.youtube.com/watch?v=Lq594XmpPBg', false, false),
('21', 'Final Fantasy XVI', 'PlayStation 5', 'RPG', 69.99, 4.6, '2023-06-22', 9, 'Un nouveau chapitre épique dans la saga Final Fantasy. Plongez dans un monde de magie et de conflits politiques, où les Égides, gardiens de cristaux, s''affrontent dans des combats spectaculaires.', '/assets/games/cover/ff16.jpg', 'https://www.youtube.com/watch?v=gV5rIW1Qums', false, false),
('22', 'Demon''s Souls', 'PlayStation 5', 'RPG', 79.99, 4.7, '2020-11-12', 7, 'Remake du classique de FromSoftware avec des graphismes next-gen. Affrontez des démons dans le royaume de Boletaria, améliorez vos compétences et survivez à l''un des jeux les plus difficiles et gratifiants jamais créés.', '/assets/games/cover/demonssouls.jpg', 'https://www.youtube.com/watch?v=2TMs2E6cms4', false, false),
('23', 'Ratchet & Clank: Rift Apart', 'PlayStation 5', 'Action', 69.99, 4.8, '2021-06-11', 11, 'Aventure interdimensionnelle avec des graphismes incroyables. Voyagez entre les dimensions, utilisez des armes créatives et sauvez la galaxie dans cette aventure palpitante de Ratchet et Clank.', '/assets/games/cover/ratchet.jpg', 'https://www.youtube.com/watch?v=ai3o0XtrnM8', true, true),
('24', 'Returnal', 'PlayStation 5', 'Action', 69.99, 4.4, '2021-04-30', 6, 'Jeu de tir roguelike third-person avec une boucle temporelle. Explorez une planète étrangère en constante évolution, où chaque mort vous ramène au début mais avec de nouvelles connaissances et possibilités.', '/assets/games/cover/returnal.jpg', 'https://www.youtube.com/watch?v=ov4fJmGCsZM', false, false),
('25', 'Gran Turismo 7', 'PlayStation 5', 'Racing', 69.99, 4.6, '2022-03-04', 13, 'Simulation de course ultime avec des centaines de voitures. Profitez de graphismes photoréalistes, d''une physique avancée et d''une collection complète de voitures dans l''expérience Gran Turismo la plus aboutie.', '/assets/games/cover/gt7.jpg', 'https://www.youtube.com/watch?v=1tBUsXIkG1A', false, false),
('26', 'Ghost of Tsushima Director''s Cut', 'PlayStation 5', 'Action', 69.99, 4.8, '2021-08-20', 10, 'Édition complète du chef-d''œuvre de Sucker Punch Productions. Devenez Jin Sakai, un samurai luttant pour libérer l''île de Tsushima de l''invasion mongole en utilisant des techniques de combat traditionnelles et de nouvelles méthodes de ghost.', '/assets/games/cover/ghost.jpg', 'https://www.youtube.com/watch?v=A5gVt028Hww', false, true),
('27', 'Death Stranding Director''s Cut', 'PlayStation 5', 'Action', 59.99, 4.3, '2021-09-24', 8, 'Édition étendue du jeu unique de Hideo Kojima. Incarnez Sam Porter Bridges dans un monde post-apocalyptique où vous devez reconnecter une Amérique dévastée en livrant des colis et en évitant des entités spectrales.', '/assets/games/cover/deathstranding.jpg', 'https://www.youtube.com/watch?v=piIgkJWDuQg', true, false),
('28', 'Sackboy: A Big Adventure', 'PlayStation 5', 'Platformer', 59.99, 4.5, '2020-11-12', 15, 'Aventure coopérative mignonne et amusante avec Sackboy. Parcourez des mondes créatifs, résolvez des énigmes et collectionnez des objets dans cette aventure plateforme colorée et imaginative.', '/assets/games/cover/sackboy.jpg', 'https://www.youtube.com/watch?v=ZOk3fj5ujNM', false, false),
('29', 'Kena: Bridge of Spirits', 'PlayStation 5', 'Action', 39.99, 4.6, '2021-09-21', 11, 'Aventure d''action-aventure avec un art magnifique et des esprits mignons. Aidez les esprits à passer dans l''au-delà en utilisant vos pouvoirs magiques et vos compagnons Rot dans ce monde enchanté.', '/assets/games/cover/kena.jpg', 'https://www.youtube.com/watch?v=pWh5388AEHw', false, false),
('30', 'The Last of Us Part I', 'PlayStation 5', 'Action', 69.99, 4.8, '2022-09-02', 9, 'Remake du chef-d''œuvre original avec des graphismes next-gen. Revivez l''histoire émotionnelle de Joel et Ellie dans un monde post-apocalyptique, avec des graphismes repensés et une jouabilité améliorée.', '/assets/games/cover/lastofus1.jpg', 'https://www.youtube.com/watch?v=R2Ebc_OFeug', false, true),
('31', 'Halo Infinite', 'Xbox', 'FPS', 59.99, 4.5, '2021-12-08', 16, 'Le retour du Master Chief dans une aventure en monde ouvert. Explorez l''anneau Halo, combattez le Banished et découvrez les secrets de l''univers Halo dans cette épique aventure spatiale.', '/assets/games/cover/halo.jpg', 'https://www.youtube.com/watch?v=PyMlV5_HRWk', false, false),
('32', 'Gears 5', 'Xbox', 'Action', 39.99, 4.6, '2019-09-10', 12, 'Continuez la lutte contre l''Essaim dans cette suite épique. Incarnez Kait Diaz et découvrez les origines du Locust dans cette aventure third-person shooter intense et émotionnelle.', '/assets/games/cover/gears5.jpg', 'https://www.youtube.com/watch?v=APqBWniRQbQ', false, false),
('33', 'Microsoft Flight Simulator', 'Xbox', 'Simulation', 59.99, 4.7, '2021-07-27', 8, 'Simulateur de vol le plus réaliste avec le monde entier. Pilotez des avions légendaires, explorez la planète entière en temps réel et vivez l''expérience ultime du vol dans cette simulation incroyablement détaillée.', '/assets/games/cover/flightsim.jpg', 'https://www.youtube.com/watch?v=TYqJALPVn0Y', false, false),
('34', 'Sea of Thieves', 'Xbox', 'Aventure', 39.99, 4.4, '2018-03-20', 20, 'Jeu de pirates multijoueur en monde ouvert. Formez votre équipage, hissez les voiles et partez à l''aventure dans un monde pirate persistant rempli de trésors, de batailles navales et de mystères.', '/assets/games/cover/seaofthieves.jpg', 'https://www.youtube.com/watch?v=r5JIBaasuE8', true, false),
('35', 'Forza Motorsport', 'Xbox', 'Racing', 69.99, 4.5, '2023-10-10', 11, 'Simulation de course sur circuit avec une physique réaliste. Profitez de graphismes next-gen, d''une physique de conduite avancée et de centaines de voitures dans la simulation de course la plus réaliste de sa génération.', '/assets/games/cover/forzamotorsport.jpg', 'https://www.youtube.com/watch?v=em4gv1Ietko', false, false),
('36', 'Psychonauts 2', 'Xbox', 'Platformer', 59.99, 4.8, '2021-08-25', 9, 'Aventure psychédélique dans les esprits des personnages. Incarnez Raz et explorez les méandres de l''esprit humain dans cette aventure plateforme unique et créative remplie d''humour et de personnages mémorables.', '/assets/games/cover/psychonauts2.jpg', 'https://www.youtube.com/watch?v=mBi9rqCZ4os', false, true),
('37', 'Grounded', 'Xbox', 'Survival', 39.99, 4.6, '2022-09-27', 13, 'Survie dans un jardin où vous êtes de la taille d''une fourmi. Construisez des bases, combattez des insectes géants et explorez un monde dangereux dans cette aventure de survie unique en perspective.', '/assets/games/cover/grounded.jpg', 'https://www.youtube.com/watch?v=ciVgq5xO5G0', true, false),
('38', 'State of Decay 2', 'Xbox', 'Survival', 29.99, 4.3, '2018-05-22', 10, 'Survie zombie avec gestion de communauté et base building. Recrutez des survivants, construisez votre base et survivez à l''apocalypse zombie dans ce jeu de survie en monde ouvert.', '/assets/games/cover/stateofdecay2.jpg', 'https://www.youtube.com/watch?v=fhj5phhsqC0', false, false),
('39', 'Splatoon 3', 'Nintendo Switch', 'Shooter', 59.99, 4.7, '2022-09-09', 16, 'Jeu de tir multijoueur coloré avec des encres et des armes uniques. Personnalisez votre Inklings, participez à des batailles territoriales et découvrez de nouvelles armes et capacités dans cet univers coloré et compétitif.', '/assets/games/cover/splatoon3.jpg', 'https://www.youtube.com/watch?v=GUYDXVDLmns', false, false),
('40', 'Super Mario Party', 'Nintendo Switch', 'Party', 59.99, 4.5, '2018-10-05', 20, 'Jeu de plateau multijoueur avec mini-jeux. Réunissez vos amis et votre famille pour des parties endiablées avec vos personnages Mario préférés dans cette collection de mini-jeux amusants et compétitifs.', '/assets/games/cover/marioparty.jpg', 'https://www.youtube.com/watch?v=by_XTria-mQ', false, false);

-- Insertion des tags des jeux (quelques exemples pour chaque jeu)
INSERT INTO game_tags (game_id, tags) VALUES
('1', 'RPG'), ('1', 'Cyberpunk'), ('1', 'Open World'), ('1', 'Futuriste'), ('1', 'Action'),
('2', 'Aventure'), ('2', 'Western'), ('2', 'Open World'), ('2', 'Action'), ('2', 'Histoire'),
('3', 'RPG'), ('3', 'Fantasy'), ('3', 'Open World'), ('3', 'Aventure'), ('3', 'Choix'),
('4', 'Action'), ('4', 'Vikings'), ('4', 'Open World'), ('4', 'Aventure'), ('4', 'Histoire'),
('5', 'Action'), ('5', 'Open World'), ('5', 'Crime'), ('5', 'Multiplayer'), ('5', 'Satire'),
('6', 'FPS'), ('6', 'Battle Royale'), ('6', 'Multiplayer'), ('6', 'Gratuit'), ('6', 'Tactical'),
('7', 'Fighting'), ('7', 'Combat'), ('7', 'Violent'), ('7', 'Multiplayer'), ('7', 'Esport'),
('8', 'Fighting'), ('8', 'Arcade'), ('8', 'Competitive'), ('8', 'Multiplayer'), ('8', 'Next-Gen'),
('9', 'Sport'), ('9', 'Football'), ('9', 'Simulation'), ('9', 'Multiplayer'), ('9', 'Realiste'),
('10', 'RPG'), ('10', 'Fantasy'), ('10', 'Turn-Based'), ('10', 'Co-op'), ('10', 'Choix'),
('11', 'FPS'), ('11', 'Tactical'), ('11', 'Competitive'), ('11', 'Gratuit'), ('11', 'Esport'),
('12', 'RPG'), ('12', 'Space'), ('12', 'Exploration'), ('12', 'Sci-Fi'), ('12', 'Open World'),
('13', 'RPG'), ('13', 'Fantasy'), ('13', 'Dark'), ('13', 'Multiplayer'), ('13', 'Action'),
('14', 'Racing'), ('14', 'Open World'), ('14', 'Cars'), ('14', 'Simulation'), ('14', 'Multiplayer'),
('15', 'RPG'), ('15', 'Zombie'), ('15', 'Horror'), ('15', 'Parkour'), ('15', 'Action'),
('16', 'Action'), ('16', 'Adventure'), ('16', 'Mythology'), ('16', 'Story-Rich'), ('16', 'Combat'),
('17', 'Action'), ('17', 'Adventure'), ('17', 'Zombie'), ('17', 'Story-Rich'), ('17', 'Emotional'),
('18', 'Sport'), ('18', 'Football'), ('18', 'Simulation'), ('18', 'Next-Gen'), ('18', 'Multiplayer'),
('19', 'Action'), ('19', 'Superhero'), ('19', 'Open World'), ('19', 'Adventure'), ('19', 'Combat'),
('20', 'Action'), ('20', 'Open World'), ('20', 'Robots'), ('20', 'Adventure'), ('20', 'RPG'),
('21', 'RPG'), ('21', 'Fantasy'), ('21', 'Story-Rich'), ('21', 'Action'), ('21', 'Adventure'),
('22', 'RPG'), ('22', 'Souls-like'), ('22', 'Difficult'), ('22', 'Fantasy'), ('22', 'Action'),
('23', 'Action'), ('23', 'Platformer'), ('23', 'Sci-Fi'), ('23', 'Adventure'), ('23', 'Shooter'),
('24', 'Action'), ('24', 'Roguelike'), ('24', 'Sci-Fi'), ('24', 'Bullet Hell'), ('24', 'Third-person'),
('25', 'Racing'), ('25', 'Simulation'), ('25', 'Cars'), ('25', 'Realistic'), ('25', 'Multiplayer'),
('26', 'Action'), ('26', 'Open World'), ('26', 'Samurai'), ('26', 'Adventure'), ('26', 'Stealth'),
('27', 'Action'), ('27', 'Adventure'), ('27', 'Sci-Fi'), ('27', 'Story-Rich'), ('27', 'Exploration'),
('28', 'Platformer'), ('28', 'Co-op'), ('28', 'Family'), ('28', 'Adventure'), ('28', 'Puzzle'),
('29', 'Action'), ('29', 'Adventure'), ('29', 'Indie'), ('29', 'Fantasy'), ('29', 'Story-Rich'),
('30', 'Action'), ('30', 'Adventure'), ('30', 'Zombie'), ('30', 'Remake'), ('30', 'Story-Rich'),
('31', 'FPS'), ('31', 'Sci-Fi'), ('31', 'Open World'), ('31', 'Multiplayer'), ('31', 'Action'),
('32', 'Action'), ('32', 'Third-person'), ('32', 'Sci-Fi'), ('32', 'Co-op'), ('32', 'Shooter'),
('33', 'Simulation'), ('33', 'Flight'), ('33', 'Realistic'), ('33', 'Open World'), ('33', 'Education'),
('34', 'Adventure'), ('34', 'Multiplayer'), ('34', 'Pirates'), ('34', 'Open World'), ('34', 'Co-op'),
('35', 'Racing'), ('35', 'Simulation'), ('35', 'Cars'), ('35', 'Realistic'), ('35', 'Multiplayer'),
('36', 'Platformer'), ('36', 'Adventure'), ('36', 'Comedy'), ('36', 'Indie'), ('36', 'Story-Rich'),
('37', 'Survival'), ('37', 'Multiplayer'), ('37', 'Crafting'), ('37', 'Adventure'), ('37', 'Base Building'),
('38', 'Survival'), ('38', 'Zombie'), ('38', 'Base Building'), ('38', 'Open World'), ('38', 'Action'),
('39', 'Shooter'), ('39', 'Multiplayer'), ('39', 'Colorful'), ('39', 'Family'), ('39', 'Competitive'),
('40', 'Party'), ('40', 'Multiplayer'), ('40', 'Family'), ('40', 'Mini-games'), ('40', 'Board Game');
-- Insertion des images des jeux (quelques exemples)
INSERT INTO game_images (game_id, images) VALUES
('1', '/assets/games/screenshots/cyberpunk1.jpg'),
('1', '/assets/games/screenshots/cyberpunk2.jpg'),
('1', '/assets/games/screenshots/cyberpunk3.jpg'),
('1', '/assets/games/screenshots/cyberpunk4.jpg'),
('2', '/assets/games/screenshots/rdr2_1.jpg'),
('2', '/assets/games/screenshots/rdr2_2.jpg'),
('2', '/assets/games/screenshots/rdr2_3.jpg'),
('2', '/assets/games/screenshots/rdr2_4.jpg'),
('3', '/assets/games/screenshots/witcher3_1.jpg'),
('3', '/assets/games/screenshots/witcher3_2.jpg'),
('3', '/assets/games/screenshots/witcher3_3.jpg'),
('3', '/assets/games/screenshots/witcher3_4.jpg'),
('4', '/assets/games/screenshots/valhalla1.jpg'),
('4', '/assets/games/screenshots/valhalla2.jpg'),
('4', '/assets/games/screenshots/valhalla3.jpg'),
('4', '/assets/games/screenshots/valhalla4.jpg'),
('5', '/assets/games/screenshots/gtav1.jpg'),
('5', '/assets/games/screenshots/gtav2.jpg'),
('5', '/assets/games/screenshots/gtav3.jpg'),
('5', '/assets/games/screenshots/gtav4.jpg'),
('6', '/assets/games/screenshots/warzone1.jpg'),
('6', '/assets/games/screenshots/warzone2.jpg'),
('6', '/assets/games/screenshots/warzone3.jpg'),
('6', '/assets/games/screenshots/warzone4.jpg'),
('7', '/assets/games/screenshots/mk11_1.jpg'),
('7', '/assets/games/screenshots/mk11_2.jpg'),
('7', '/assets/games/screenshots/mk11_3.jpg'),
('7', '/assets/games/screenshots/mk11_4.jpg'),
('8', '/assets/games/screenshots/sf6_1.jpg'),
('8', '/assets/games/screenshots/sf6_2.jpg'),
('8', '/assets/games/screenshots/sf6_3.jpg'),
('8', '/assets/games/screenshots/sf6_4.jpg'),
('9', '/assets/games/screenshots/fc24_1.jpg'),
('9', '/assets/games/screenshots/fc24_2.jpg'),
('9', '/assets/games/screenshots/fc24_3.jpg'),
('9', '/assets/games/screenshots/fc24_4.jpg'),
('10', '/assets/games/screenshots/baldurs1.jpg'),
('10', '/assets/games/screenshots/baldurs2.jpg'),
('10', '/assets/games/screenshots/baldurs3.jpg'),
('10', '/assets/games/screenshots/baldurs4.jpg'),
('11', '/assets/games/screenshots/valorant1.jpg'),
('11', '/assets/games/screenshots/valorant2.jpg'),
('11', '/assets/games/screenshots/valorant3.jpg'),
('11', '/assets/games/screenshots/valorant4.jpg'),
('12', '/assets/games/screenshots/starfield1.jpg'),
('12', '/assets/games/screenshots/starfield2.jpg'),
('12', '/assets/games/screenshots/starfield3.jpg'),
('12', '/assets/games/screenshots/starfield4.jpg'),
('13', '/assets/games/screenshots/diablo4_1.jpg'),
('13', '/assets/games/screenshots/diablo4_2.jpg'),
('13', '/assets/games/screenshots/diablo4_3.jpg'),
('13', '/assets/games/screenshots/diablo4_4.jpg'),
('14', '/assets/games/screenshots/forza5_1.jpg'),
('14', '/assets/games/screenshots/forza5_2.jpg'),
('14', '/assets/games/screenshots/forza5_3.jpg'),
('14', '/assets/games/screenshots/forza5_4.jpg'),
('15', '/assets/games/screenshots/dyinglight1.jpg'),
('15', '/assets/games/screenshots/dyinglight2.jpg'),
('15', '/assets/games/screenshots/dyinglight3.jpg'),
('15', '/assets/games/screenshots/dyinglight4.jpg'),
('16', '/assets/games/screenshots/gow_1.jpg'),
('16', '/assets/games/screenshots/gow_2.jpg'),
('16', '/assets/games/screenshots/gow_3.jpg'),
('16', '/assets/games/screenshots/gow_4.jpg'),
('17', '/assets/games/screenshots/tlou2_1.jpg'),
('17', '/assets/games/screenshots/tlou2_2.jpg'),
('17', '/assets/games/screenshots/tlou2_3.jpg'),
('17', '/assets/games/screenshots/tlou2_4.jpg'),
('18', '/assets/games/screenshots/fc25_1.jpg'),
('18', '/assets/games/screenshots/fc25_2.jpg'),
('18', '/assets/games/screenshots/fc25_3.jpg'),
('18', '/assets/games/screenshots/fc25_4.jpg'),
('18', '/assets/games/screenshots/fc25_5.jpg'),
('18', '/assets/games/screenshots/fc25_6.jpg'),
('19', '/assets/games/screenshots/spiderman2_1.png'),
('19', '/assets/games/screenshots/spiderman2_2.png'),
('19', '/assets/games/screenshots/spiderman2_3.png'),
('19', '/assets/games/screenshots/spiderman2_4.png'),
('20', '/assets/games/screenshots/horizon2_1.png'),
('20', '/assets/games/screenshots/horizon2_2.png'),
('20', '/assets/games/screenshots/horizon2_3.png'),
('20', '/assets/games/screenshots/horizon2_4.png'),
('21', '/assets/games/screenshots/ff16_1.jpg'),
('21', '/assets/games/screenshots/ff16_2.jpg'),
('21', '/assets/games/screenshots/ff16_3.jpg'),
('21', '/assets/games/screenshots/ff16_4.jpg'),
('22', '/assets/games/screenshots/demonssouls1.jpg'),
('22', '/assets/games/screenshots/demonssouls2.jpg'),
('22', '/assets/games/screenshots/demonssouls3.jpg'),
('22', '/assets/games/screenshots/demonssouls4.jpg'),
('23', '/assets/games/screenshots/ratchet1.png'),
('23', '/assets/games/screenshots/ratchet2.png'),
('23', '/assets/games/screenshots/ratchet3.png'),
('23', '/assets/games/screenshots/ratchet4.png'),
('24', '/assets/games/screenshots/returnal1.png'),
('24', '/assets/games/screenshots/returnal2.png'),
('24', '/assets/games/screenshots/returnal3.png'),
('24', '/assets/games/screenshots/returnal4.png'),
('25', '/assets/games/screenshots/gt7_1.jpg'),
('25', '/assets/games/screenshots/gt7_2.jpg'),
('25', '/assets/games/screenshots/gt7_3.jpg'),
('25', '/assets/games/screenshots/gt7_4.jpg'),
('26', '/assets/games/screenshots/ghost1.jpg'),
('26', '/assets/games/screenshots/ghost2.jpg'),
('26', '/assets/games/screenshots/ghost3.jpg'),
('26', '/assets/games/screenshots/ghost4.jpg'),
('27', '/assets/games/screenshots/deathstranding1.jpg'),
('27', '/assets/games/screenshots/deathstranding2.jpg'),
('27', '/assets/games/screenshots/deathstranding3.jpg'),
('27', '/assets/games/screenshots/deathstranding4.jpg'),
('28', '/assets/games/screenshots/sackboy1.jpg'),
('28', '/assets/games/screenshots/sackboy2.jpg'),
('28', '/assets/games/screenshots/sackboy3.jpg'),
('28', '/assets/games/screenshots/sackboy4.jpg'),
('29', '/assets/games/screenshots/kena1.png'),
('29', '/assets/games/screenshots/kena2.png'),
('29', '/assets/games/screenshots/kena3.png'),
('29', '/assets/games/screenshots/kena4.png'),
('30', '/assets/games/screenshots/tlou1_1.png'),
('30', '/assets/games/screenshots/tlou1_2.png'),
('30', '/assets/games/screenshots/tlou1_3.png'),
('30', '/assets/games/screenshots/tlou1_4.png'),
('31', '/assets/games/screenshots/halo1.png'),
('31', '/assets/games/screenshots/halo2.png'),
('31', '/assets/games/screenshots/halo3.png'),
('31', '/assets/games/screenshots/halo4.png'),
('32', '/assets/games/screenshots/gears5_1.png'),
('32', '/assets/games/screenshots/gears5_2.png'),
('32', '/assets/games/screenshots/gears5_3.png'),
('32', '/assets/games/screenshots/gears5_4.png'),
('33', '/assets/games/screenshots/flightsim1.jpg'),
('33', '/assets/games/screenshots/flightsim2.jpg'),
('33', '/assets/games/screenshots/flightsim3.jpg'),
('33', '/assets/games/screenshots/flightsim4.jpg'),
('34', '/assets/games/screenshots/seaofthieves1.jpg'),
('34', '/assets/games/screenshots/seaofthieves2.jpg'),
('34', '/assets/games/screenshots/seaofthieves3.jpg'),
('34', '/assets/games/screenshots/seaofthieves4.jpg'),
('35', '/assets/games/screenshots/forzamotorsport1.jpg'),
('35', '/assets/games/screenshots/forzamotorsport2.jpg'),
('35', '/assets/games/screenshots/forzamotorsport3.jpg'),
('35', '/assets/games/screenshots/forzamotorsport4.jpg'),
('36', '/assets/games/screenshots/psychonauts1.png'),
('36', '/assets/games/screenshots/psychonauts2.png'),
('36', '/assets/games/screenshots/psychonauts3.png'),
('36', '/assets/games/screenshots/psychonauts4.png'),
('37', '/assets/games/screenshots/grounded1.jpg'),
('37', '/assets/games/screenshots/grounded2.jpg'),
('37', '/assets/games/screenshots/grounded3.jpg'),
('37', '/assets/games/screenshots/grounded4.jpg'),
('38', '/assets/games/screenshots/stateofdecay1.jpg'),
('38', '/assets/games/screenshots/stateofdecay2.jpg'),
('38', '/assets/games/screenshots/stateofdecay3.jpg'),
('38', '/assets/games/screenshots/stateofdecay4.jpg'),
('39', '/assets/games/screenshots/splatoon1.jpg'),
('39', '/assets/games/screenshots/splatoon2.jpg'),
('39', '/assets/games/screenshots/splatoon3.jpg'),
('39', '/assets/games/screenshots/splatoon4.jpg'),
('40', '/assets/games/screenshots/marioparty1.jpg'),
('40', '/assets/games/screenshots/marioparty2.jpg'),
('40', '/assets/games/screenshots/marioparty3.jpg'),
('40', '/assets/games/screenshots/marioparty4.jpg');

-- Insertion des utilisateurs
INSERT INTO users (id, email, password, nom, prenom, adresse) VALUES
('1', 'amine@example.com', '123456', 'Manai', 'Mohamed Amine', 'Mornaguia'),
('46a4', 'amine@test.com', 'amine6', 'manai', 'amine', 'tunis'),
('ae02',  'sdsadsad@fjads.vpa', 'aaaaaa', 'amine', 'amine', 'aaa'),
('V3QiRyK', 'amine@test2.com', 'amine1', 'amine', 'manai', 'tunis');

-- Insertion des adresses
INSERT INTO addresses (id, nom, rue, ville, code_postal, pays, user_id, is_default) VALUES
('c2f1', 'mornaguia', '04', 'mornaguia', '1110', 'tunisie', '1', true),
('44db', 'tunis', 'tunis', 'tunis', '1112', 'tunisie', '1', false);

-- Insertion des commandes
INSERT INTO orders (id, user_id, date, total, status, address_id) VALUES
(1, '1', '2025-11-03 23:08:13.015', 54.99, 'completed', 'c2f1'),
(2, '1', '2025-11-03 23:17:26.267', 104.98, 'completed', 'c2f1'),
(3, '1', '2025-11-04 11:49:43.864', 104.98, 'completed', 'c2f1');

-- Insertion des articles de commande
INSERT INTO order_items (game_id, quantity, price, order_id) VALUES
('3', 1, 39.99, 1),
('2', 1, 49.99, 2),
('3', 1, 39.99, 2),
('2', 1, 49.99, 3),
('32', 1, 39.99, 3);



-- ============================================================================
-- TABLE REVIEWS COMPLÈTE
-- ============================================================================

INSERT INTO reviews (id, game_id, user_id, msg, note, date, verified) VALUES
('rev1', '1', '1', 'Incroyable ! L''atmosphère de Night City est unique. Johnny Silverhand rend l''expérience mémorable.', 5, '2024-01-15 10:30:00', true),
('rev2', '1', '1', 'Très bon RPG, même si quelques bugs persistent. Le monde ouvert est immense et détaillé.', 4, '2024-02-20 14:45:00', true),
('rev3', '2', '1', 'Chef-d''œuvre absolu ! L''histoire d''Arthur Morgan est la meilleure que j''ai jamais vue dans un jeu vidéo.', 5, '2024-03-10 09:15:00', true),
('rev4', '2', '1', 'La narration et l''immersion sont exceptionnelles. Un must-play pour tout gamer.', 5, '2024-02-28 16:20:00', true),
('rev5', '3', '1', 'Le meilleur RPG de tous les temps ! Les quêtes secondaires sont aussi bonnes que l''histoire principale.', 5, '2024-01-22 16:20:00', true),
('rev6', '3', '1', 'Même après 200h de jeu, je découvre encore de nouvelles choses. Absolument parfait !', 5, '2024-02-15 11:30:00', true),
('rev7', '4', '1', 'Excellent jeu, l''époque viking est bien retranscrite. Les raids sont très amusants !', 4, '2024-03-05 13:45:00', true),
('rev8', '4', '1', 'Graphismes magnifiques et gameplay solide. La colonie apporte une bonne dimension.', 4, '2024-03-12 10:30:00', true),
('rev9', '5', '1', 'Incontournable ! Même après toutes ces années, GTA V reste une référence du jeu en monde ouvert.', 5, '2024-01-30 08:20:00', true),
('rev10', '5', '1', 'Le mode histoire est excellent, GTA Online offre un contenu quasi infini.', 4, '2024-02-18 15:10:00', true),
('rev11', '6', '1', 'Battle Royale intense mais équilibré. Parfait pour jouer entre amis.', 4, '2024-02-10 14:25:00', true),
('rev12', '6', '1', 'Gratuit et très complet. Les mises à jour régulières maintiennent l''intérêt.', 5, '2024-03-01 11:45:00', true),
('rev13', '7', '1', 'Violent comme d''habitude mais très amusant entre amis. Les fatalities sont créatives !', 4, '2024-03-15 16:40:00', true),
('rev14', '7', '1', 'Le meilleur Mortal Kombat à ce jour. Graphismes époustouflants.', 5, '2024-02-22 09:30:00', true),
('rev15', '8', '1', 'Street Fighter revient en force ! Le nouveau système de combat est excellent.', 5, '2024-03-18 13:15:00', true),
('rev16', '8', '1', 'Très bon jeu de combat, accessible aux débutants tout en gardant de la profondeur.', 4, '2024-03-25 17:20:00', true),
('rev17', '9', '1', 'Le meilleur jeu de football actuellement. Très réaliste !', 5, '2024-03-18 13:25:00', true),
('rev18', '9', '1', 'Transition réussie vers EA Sports FC. Les améliorations sont notables.', 4, '2024-04-02 10:10:00', true),
('rev19', '10', '1', 'Le RPG de la décennie ! La liberté offerte au joueur est sans précédent.', 5, '2024-03-12 12:00:00', true),
('rev20', '10', '1', 'Incroyablement profond, chaque partie est unique. Un chef-d''œuvre !', 5, '2024-03-20 10:45:00', true),
('rev21', '11', '1', 'FPS tactique excellent. L''équilibre entre les agents est bien pensé.', 4, '2024-02-14 15:30:00', true),
('rev22', '11', '1', 'Gratuit et très compétitif. La communauté est active.', 5, '2024-03-08 12:45:00', true),
('rev23', '12', '1', 'Ambiance space opera réussie. L''exploration est très satisfaisante.', 4, '2024-03-22 14:20:00', true),
('rev24', '12', '1', 'Bethesda fait du Bethesda, on aime ou on n''aime pas. Personnellement, j''adore !', 4, '2024-04-05 11:35:00', true),
('rev25', '13', '1', 'Retour réussi de Diablo. Le endgame est addictif.', 5, '2024-02-28 13:50:00', true),
('rev26', '13', '1', 'Très bon ARPG, même si le contenu de base manque un peu.', 4, '2024-03-15 16:25:00', true),
('rev27', '14', '1', 'Les graphismes sont incroyables et la sensation de conduite est parfaite !', 5, '2024-02-25 17:30:00', true),
('rev28', '14', '1', 'Le meilleur Forza Horizon à ce jour. Le Mexique est magnifique.', 5, '2024-03-10 09:45:00', true),
('rev29', '15', '1', 'Suite très réussie. Le parkour et le combat sont améliorés.', 4, '2024-03-28 12:15:00', true),
('rev30', '15', '1', 'Monde ouvert passionnant. La nuit, l''ambiance devient vraiment angoissante.', 5, '2024-04-08 14:40:00', true),
('rev31', '16', '1', 'L''évolution de Kratos est magnifique. Graphismes et gameplay au top !', 5, '2024-03-08 14:20:00', true),
('rev32', '16', '1', 'Suite parfaite du premier opus. L''histoire est émouvante.', 5, '2024-03-25 10:30:00', true),
('rev33', '17', '1', 'Narratif incroyable. Les performances des acteurs sont exceptionnelles.', 5, '2024-02-18 11:25:00', true),
('rev34', '17', '1', 'Jeu poignant qui ne laisse pas indifférent. Les choix sont difficiles.', 5, '2024-03-12 15:50:00', true),
('rev35', '18', '1', 'Améliorations techniques notables. Le gameplay est plus fluide.', 4, '2024-04-01 13:20:00', true),
('rev36', '18', '1', 'Bonne évolution de la franchise. Les nouvelles mécaniques sont intéressantes.', 4, '2024-04-10 16:45:00', true),
('rev37', '19', '1', 'Spider-Man 2 est tout simplement parfait. Le swinging est addictif !', 5, '2024-03-15 14:30:00', true),
('rev38', '19', '1', 'Graphismes époustouflants et histoire captivante. Un must-have PS5.', 5, '2024-03-28 17:15:00', true),
('rev39', '20', '1', 'Suite réussie. Les nouveaux environnements sont magnifiques.', 4, '2024-02-22 12:40:00', true),
('rev40', '20', '1', 'Aloy reste un personnage attachant. Le combat contre les machines est amélioré.', 5, '2024-03-05 10:25:00', true),
('rev41', '21', '1', 'Final Fantasy revient avec un bang ! Le combat en temps réel est excellent.', 5, '2024-03-18 13:45:00', true),
('rev42', '21', '1', 'Histoire épique et combats spectaculaires. Les Eikons sont incroyables.', 5, '2024-04-02 15:20:00', true),
('rev43', '22', '1', 'Remake magnifique d''un classique. La difficulté est toujours au rendez-vous.', 5, '2024-02-29 11:30:00', true),
('rev44', '22', '1', 'Graphismes next-gen pour ce chef-d''œuvre. Les amateurs de Souls apprécieront.', 4, '2024-03-14 14:55:00', true),
('rev45', '23', '1', 'Aventure colorée et amusante. Les transitions dimensionnelles sont impressionnantes.', 5, '2024-03-22 16:10:00', true),
('rev46', '23', '1', 'Parfait pour montrer la puissance de la PS5. Très créatif !', 5, '2024-04-05 12:25:00', true),
('rev47', '24', '1', 'Roguelike intense et technique. La boucle de gameplay est addictive.', 4, '2024-03-08 09:40:00', true),
('rev48', '24', '1', 'Difficile mais gratifiant. L''histoire est intrigante.', 4, '2024-03-20 13:15:00', true),
('rev49', '25', '1', 'Simulation de course ultime. Le réalisme est impressionnant.', 5, '2024-03-25 15:50:00', true),
('rev50', '25', '1', 'Gran Turismo dans sa plus pure tradition. Les puristes vont adorer.', 5, '2024-04-08 11:20:00', true),
('rev51', '26', '1', 'Édition Director''s Cut impeccable. L''île d''Iki est un excellent ajout.', 5, '2024-02-15 14:45:00', true),
('rev52', '26', '1', 'Le plus beau jeu de samouraï jamais créé. La direction artistique est sublime.', 5, '2024-03-01 17:30:00', true),
('rev53', '27', '1', 'Expérience unique comme seul Kojima sait les faire. Le Director''s Cut améliore l''expérience.', 4, '2024-03-28 10:15:00', true),
('rev54', '27', '1', 'Jeu bizarre mais fascinant. La livraison de colis n''a jamais été aussi prenante.', 4, '2024-04-12 13:40:00', true),
('rev55', '28', '1', 'Parfait pour jouer en famille. Les mini-jeux sont variés et amusants.', 5, '2024-03-05 16:25:00', true),
('rev56', '28', '1', 'Sackboy toujours aussi attachant. La coopération est excellente.', 4, '2024-03-18 12:50:00', true),
('rev57', '29', '1', 'Graphismes magnifiques style Pixar. L''aventure est touchante.', 5, '2024-03-22 15:35:00', true),
('rev58', '29', '1', 'Surprenant et rafraîchissant. Les Rot sont trop mignons !', 4, '2024-04-05 14:20:00', true),
('rev59', '30', '1', 'Remake fidèle avec des graphismes magnifiques. Revivre cette histoire en next-gen est un plaisir.', 5, '2024-03-15 11:45:00', true),
('rev60', '30', '1', 'La relation Joel-Ellie reste aussi émouvante. Les améliorations techniques sont bienvenues.', 5, '2024-03-29 16:10:00', true),
('rev61', '31', '1', 'Le retour du Master Chief ! Le monde ouvert apporte une nouvelle dimension à Halo.', 4, '2024-02-20 13:25:00', true),
('rev62', '31', '1', 'Campagne solide et multijoueur gratuit. Que demander de plus ?', 5, '2024-03-08 10:40:00', true),
('rev63', '32', '1', 'Gears 5 continue la tradition d''excellence. Le combat est toujours aussi satisfaisant.', 4, '2024-03-25 14:55:00', true),
('rev64', '32', '1', 'Suite émouvante qui explore les origines du Locust. Le gameplay coop est excellent.', 5, '2024-04-10 12:30:00', true),
('rev65', '33', '1', 'Simulateur de vol le plus réaliste jamais créé. Voler autour de sa maison est magique.', 5, '2024-03-12 15:15:00', true),
('rev66', '33', '1', 'Incroyablement détaillé. Parfait pour les passionnés d''aviation.', 5, '2024-03-28 17:40:00', true),
('rev67', '34', '1', 'Jeu de pirates ultime. Les batailles navales sont épiques !', 5, '2024-02-25 11:50:00', true),
('rev68', '34', '1', 'Mieux avec des amis. L''exploration des îles et la chasse au trésor sont très amusantes.', 4, '2024-03-18 14:25:00', true),
('rev69', '35', '1', 'Simulation pure et dure. La physique de conduite est impeccable.', 5, '2024-04-02 16:50:00', true),
('rev70', '35', '1', 'Retour aux sources réussi. Les puristes de la simulation seront comblés.', 4, '2024-04-15 13:35:00', true),
('rev71', '36', '1', 'Psychonauts 2 est une pépite ! Drôle, créatif et touchant.', 5, '2024-03-22 12:10:00', true),
('rev72', '36', '1', 'Suite qui honore parfaitement le premier opus. L''humour est excellent.', 5, '2024-04-08 15:45:00', true),
('rev73', '37', '1', 'Concept original et bien exécuté. Survivre dans un jardin géant est passionnant.', 4, '2024-03-15 10:20:00', true),
('rev74', '37', '1', 'Survie coopérative très amusante. Les insectes géants sont impressionnants.', 5, '2024-03-29 14:55:00', true),
('rev75', '38', '1', 'Bon jeu de survie zombie. La gestion de la communauté ajoute de la profondeur.', 4, '2024-02-28 13:30:00', true),
('rev76', '38', '1', 'Amélioration notable du premier opus. Le monde ouvert est plus varié.', 4, '2024-03-12 16:05:00', true),
('rev77', '39', '1', 'Splatoon 3 perfectionne la formule. Les nouvelles armes sont géniales.', 5, '2024-03-25 11:40:00', true),
('rev78', '39', '1', 'Coloré, fun et compétitif. Parfait pour des parties rapides.', 5, '2024-04-10 14:15:00', true),
('rev79', '40', '1', 'Jeu de party parfait pour les soirées entre amis. Les mini-jeux sont variés.', 5, '2024-03-08 17:50:00', true),
('rev80', '40', '1', 'Mario Party comme on l''aime. Les nouveaux plateaux sont excellents.', 4, '2024-03-22 15:25:00', true),
('CyQfRsr', '12', '1', 'beaux jeu', 5, '2025-11-10 20:14:29.879', true),
('7FVo9Ng', '1', '1', 'beau jeu', 3, '2025-11-10 20:15:08.113', true);
-- Insertion dans la wishlist
INSERT INTO user_wishlist (user_id, wishlist) VALUES
('1', '3'),
('1', '5'),
('1', '10'),
('1', '15'),
('1', '20');